import { createSvgIconFromRaw } from './base';

import githubSvg from './svg/github.svg?raw';
import gitBranchSvg from './svg/git-branch.svg?raw';
import gitPullRequestSvg from './svg/git-pull-request.svg?raw';
import gitCommitSvg from './svg/git-commit.svg?raw';
import gitMergeSvg from './svg/git-merge.svg?raw';
import gitForkSvg from './svg/git-fork.svg?raw';
import circleDotSvg from './svg/circle-dot.svg?raw';
import playCircleSvg from './svg/play-circle.svg?raw';
import barChart2Svg from './svg/bar-chart-2.svg?raw';
import historySvg from './svg/history.svg?raw';
import checkCircle2Svg from './svg/check-circle-2.svg?raw';
import xCircleSvg from './svg/x-circle.svg?raw';
import alertCircleSvg from './svg/alert-circle.svg?raw';
import shieldSvg from './svg/shield.svg?raw';
import shieldCheckSvg from './svg/shield-check.svg?raw';

export const Github = createSvgIconFromRaw(githubSvg, 'Github');
export const GitBranch = createSvgIconFromRaw(gitBranchSvg, 'GitBranch');
export const GitPullRequest = createSvgIconFromRaw(gitPullRequestSvg, 'GitPullRequest');
export const GitCommit = createSvgIconFromRaw(gitCommitSvg, 'GitCommit');
export const GitMerge = createSvgIconFromRaw(gitMergeSvg, 'GitMerge');
export const GitFork = createSvgIconFromRaw(gitForkSvg, 'GitFork');
export const CircleDot = createSvgIconFromRaw(circleDotSvg, 'CircleDot');
export const PlayCircle = createSvgIconFromRaw(playCircleSvg, 'PlayCircle');
export const BarChart2 = createSvgIconFromRaw(barChart2Svg, 'BarChart2');
export const History = createSvgIconFromRaw(historySvg, 'History');
export const CheckCircle2 = createSvgIconFromRaw(checkCircle2Svg, 'CheckCircle2');
export const XCircle = createSvgIconFromRaw(xCircleSvg, 'XCircle');
export const AlertCircle = createSvgIconFromRaw(alertCircleSvg, 'AlertCircle');
export const Shield = createSvgIconFromRaw(shieldSvg, 'Shield');
export const ShieldCheck = createSvgIconFromRaw(shieldCheckSvg, 'ShieldCheck');
