import { createSvgIconFromRaw } from './base';

import searchSvg from './svg/search.svg?raw';
import bellSvg from './svg/bell.svg?raw';
import plusSvg from './svg/plus.svg?raw';
import bookmarkSvg from './svg/bookmark.svg?raw';
import terminalSvg from './svg/terminal.svg?raw';
import sunSvg from './svg/sun.svg?raw';
import moonSvg from './svg/moon.svg?raw';
import sparklesSvg from './svg/sparkles.svg?raw';
import xSvg from './svg/x.svg?raw';
import chevronDownSvg from './svg/chevron-down.svg?raw';
import chevronRightSvg from './svg/chevron-right.svg?raw';
import checkSvg from './svg/check.svg?raw';
import copySvg from './svg/copy.svg?raw';
import starSvg from './svg/star.svg?raw';
import eyeSvg from './svg/eye.svg?raw';
import heartSvg from './svg/heart.svg?raw';
import pinSvg from './svg/pin.svg?raw';
import externalLinkSvg from './svg/external-link.svg?raw';
import refreshCwSvg from './svg/refresh-cw.svg?raw';
import scaleSvg from './svg/scale.svg?raw';
import arrowLeftSvg from './svg/arrow-left.svg?raw';
import edit3Svg from './svg/edit-3.svg?raw';
import loader2Svg from './svg/loader-2.svg?raw';
import zapSvg from './svg/zap.svg?raw';
import cornerDownLeftSvg from './svg/corner-down-left.svg?raw';
import sendSvg from './svg/send.svg?raw';
import downloadSvg from './svg/download.svg?raw';

export const Search = createSvgIconFromRaw(searchSvg, 'Search');
export const Bell = createSvgIconFromRaw(bellSvg, 'Bell');
export const Plus = createSvgIconFromRaw(plusSvg, 'Plus');
export const Bookmark = createSvgIconFromRaw(bookmarkSvg, 'Bookmark');
export const Terminal = createSvgIconFromRaw(terminalSvg, 'Terminal');
export const Sun = createSvgIconFromRaw(sunSvg, 'Sun');
export const Moon = createSvgIconFromRaw(moonSvg, 'Moon');
export const Sparkles = createSvgIconFromRaw(sparklesSvg, 'Sparkles');
export const X = createSvgIconFromRaw(xSvg, 'X');
export const ChevronDown = createSvgIconFromRaw(chevronDownSvg, 'ChevronDown');
export const ChevronRight = createSvgIconFromRaw(chevronRightSvg, 'ChevronRight');
export const Check = createSvgIconFromRaw(checkSvg, 'Check');
export const Copy = createSvgIconFromRaw(copySvg, 'Copy');
export const Star = createSvgIconFromRaw(starSvg, 'Star');
export const Eye = createSvgIconFromRaw(eyeSvg, 'Eye');
export const Heart = createSvgIconFromRaw(heartSvg, 'Heart');
export const Pin = createSvgIconFromRaw(pinSvg, 'Pin');
export const ExternalLink = createSvgIconFromRaw(externalLinkSvg, 'ExternalLink');
export const RefreshCw = createSvgIconFromRaw(refreshCwSvg, 'RefreshCw');
export const Scale = createSvgIconFromRaw(scaleSvg, 'Scale');
export const ArrowLeft = createSvgIconFromRaw(arrowLeftSvg, 'ArrowLeft');
export const Edit3 = createSvgIconFromRaw(edit3Svg, 'Edit3');
export const Loader2 = createSvgIconFromRaw(loader2Svg, 'Loader2');
export const Zap = createSvgIconFromRaw(zapSvg, 'Zap');
export const CornerDownLeft = createSvgIconFromRaw(cornerDownLeftSvg, 'CornerDownLeft');
export const Send = createSvgIconFromRaw(sendSvg, 'Send');
export const Download = createSvgIconFromRaw(downloadSvg, 'Download');
