import { ActionWorkflowRun } from './types';

export const INITIAL_WORKFLOW_RUNS: ActionWorkflowRun[] = [
  {
    id: 'run-10492',
    workflowName: 'CI / Node.js Test & Lint Suite',
    eventName: 'push',
    branch: 'main',
    commitHash: '8f921bc',
    commitMessage: 'feat(ui): migrate components to modern layout system',
    author: 'luxarion',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    status: 'completed',
    conclusion: 'success',
    startedAt: '12 minutes ago',
    duration: '1m 24s',
    steps: [
      {
        name: 'Set up job & runner environment (ubuntu-latest)',
        status: 'completed',
        duration: '4s',
        logs: [
          'Virtual Environment: Linux runner-az-49 6.8.0-1017-azure #20-Ubuntu',
          'Included Software: Node.js 22.14.0, pnpm 9.15.0, git 2.43.0',
          'Primary repository initialized in /home/runner/work/modern-github',
        ],
      },
      {
        name: 'Checkout source code',
        status: 'completed',
        duration: '3s',
        logs: [
          'Syncing repository: luxarion/modern-github',
          'Getting Git data from origin at branch main',
          'HEAD is now at 8f921bc feat(ui): migrate components to modern layout system',
        ],
      },
      {
        name: 'Install dependencies via pnpm',
        status: 'completed',
        duration: '18s',
        logs: [
          'Resolving dependencies...',
          'Packages: +412',
          '++++++++++++++++++++++++++++++++++++++++++++',
          'Progress: resolved 412, reused 380, downloaded 32',
          'Done in 17.8s',
        ],
      },
      {
        name: 'Execute TypeScript Typecheck & Linter',
        status: 'completed',
        duration: '12s',
        logs: [
          '> tsc --noEmit',
          'Found 0 errors across 48 source files.',
          '> eslint src/ --ext .ts,.tsx',
          '✨  All rules passed without warnings.',
        ],
      },
      {
        name: 'Run unit & integration test suites',
        status: 'completed',
        duration: '22s',
        logs: [
          'PASS src/engine/diffEngine.test.ts (6 tests, 12ms)',
          'PASS src/engine/gitEngine.test.ts (14 tests, 48ms)',
          'PASS src/features/code-explorer/viewer.test.tsx (8 tests, 35ms)',
          'Test Suites: 8 passed, 8 total',
          'Tests:       42 passed, 42 total',
          'Snapshots:   0 total',
          'Time:        3.124 s',
        ],
      },
      {
        name: 'Build production artifacts (Vite & ESBuild)',
        status: 'completed',
        duration: '25s',
        logs: [
          '> vite build',
          'dist/index.html                   1.42 kB │ gzip:  0.64 kB',
          'dist/assets/index-DkL3m9p.css    24.18 kB │ gzip:  5.82 kB',
          'dist/assets/index-B7j9xqA.js    182.44 kB │ gzip: 58.12 kB',
          '✓ built in 1.48s',
        ],
      },
    ],
  },
  {
    id: 'run-10491',
    workflowName: 'CodeQL Security & Vulnerability Analysis',
    eventName: 'pull_request',
    branch: 'feat/modern-redesign',
    commitHash: '3c819fa',
    commitMessage: 'fix(engine): optimize diff chunking algorithm for large files',
    author: 'sarah-dev',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    status: 'completed',
    conclusion: 'success',
    startedAt: '1 hour ago',
    duration: '2m 10s',
    steps: [
      {
        name: 'Initialize CodeQL scanner',
        status: 'completed',
        duration: '12s',
        logs: ['Initializing query packs for javascript/typescript', 'Rule set: github/security-extended'],
      },
      {
        name: 'Perform AST Deep Analysis',
        status: 'completed',
        duration: '1m 45s',
        logs: ['Analyzed 8,420 lines of code across 32 modules', 'Zero critical security vulnerabilities detected.'],
      },
    ],
  },
  {
    id: 'run-10490',
    workflowName: 'Deploy Preview to Cloud Run Edge',
    eventName: 'workflow_dispatch',
    branch: 'main',
    commitHash: '7a1102e',
    commitMessage: 'chore(release): bump version to v2.4.0',
    author: 'luxarion',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    status: 'completed',
    conclusion: 'success',
    startedAt: '3 hours ago',
    duration: '48s',
    steps: [
      {
        name: 'Authenticate with Google Cloud Service Account',
        status: 'completed',
        duration: '5s',
        logs: ['OIDC token authenticated for service github-actions@cloudbuild.iam.gserviceaccount.com'],
      },
      {
        name: 'Deploy container image to Cloud Run',
        status: 'completed',
        duration: '43s',
        logs: [
          'Service [modern-github-preview] revision [modern-github-preview-00042] has been deployed.',
          'Routing 100% traffic to revision modern-github-preview-00042.',
          'Endpoint: https://modern-github-preview-asia.run.app',
        ],
      },
    ],
  },
];
